### ISSUE TITLE
不能使用哦。

### ISSUE THREAD

**Issue by superglg738** [maiff/Itchat#4]
let uuid = res.text.match(/\"(.+)\"/)[1]
                   ^

TypeError: Cannot read property 'text' of undefined
    at request.get.end (D:\Js\Itchat\lib\getUuid.js:12:20)
    at Request.callback (D:\Js\Itchat\node_modules\superagent\lib\node\index.js:728:3)
    at ClientRequest.req.once.err (D:\Js\Itchat\node_modules\superagent\lib\node\index.js:647:10)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)

感觉是不是 那个 uuidUrl的问题。
这个工程怎么执行哦。。。

**Comment by maiff** [comment]
应该是weixin的接口更新了，作者已经没有精力更新了

**Comment by superglg738** [comment]
唉。 搞了半天是网络的问题。 内网代理 vscode这个微信https地址出不去，在外网机子上没有问题。 
谢谢了。
